=== RyderRaymond/assignment-1--databases--cs-365--fall-2024/xml/student.dtd
<!-- ========================================================================
student-database is the root element.

XML can only have one root element, so there needs to be something to hold
all of the students. This has to contain one or more student.
==========================================================================-->
<!ELEMENT student-database (student+)>

<!-- ========================================================================
Represents a student, and all of their information.

Contains elements for the name information, contact-info, and enrollment-info
==========================================================================-->
<!ELEMENT student (name, contact-info, enrollment-info)>

<!-- ========================================================================
Holds the information pertaining to the student's name.

Students must have a first name, middle name, last name, and preferred name.

Rather than stating that students can have zero or one middle names
and preferred names, it is required to have these elements, but they can
be left blank if the student does not have that information.
==========================================================================-->
<!ELEMENT name (first-name, middle-name, last-name, preferred-name)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT preferred-name (#PCDATA)>

<!-- ========================================================================
Contact info will contain the student's email and phone number as required
attributes.
==========================================================================-->
<!ELEMENT contact-info EMPTY>

<!-- ========================================================================
Enrollment info contains the student's GPA, at least one major and zero or
more minors, an advisor, the date they enrolled, and the date they graduated
on or will graduate on.
==========================================================================-->
<!ELEMENT enrollment-info (gpa, major+, minor*, advisor, date-enrolled, graduation-date)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT date-enrolled (#PCDATA)>
<!ELEMENT graduation-date (#PCDATA)>

<!-- ========================================================================
Students have an ID attribute to easily and quickly differentiate between
students, because IDs are unique to each student.

The ID data type requires starting with a character and not a digit.
I start each student ID with "id-" and then put the actual student ID.

Ideally the DTD could reflect the requirement to start with "id-" and then
the rest be the actual ID, but I do not know if there is a way to
implement this. Also, the CSS should be set to remove the "id-", but I did not
know how to do something like this in CSS, so this is why the "id-" is left in.
==========================================================================-->
<!ATTLIST student id ID #REQUIRED>

<!-- ========================================================================
Contact info must contain an email and phone.
==========================================================================-->
<!ATTLIST contact-info
          email CDATA #REQUIRED
          phone CDATA #REQUIRED>

<!-- ========================================================================
Enrollment info also contains the status of what year students are in,
and their status as to whether they are graduated or still enrolled as
part time or full time.

Having these as attributes limits the options to only valid statuses,
instead of regular text.
==========================================================================-->
<!ATTLIST enrollment-info
          year-status (first-year|second-year|third-year|fourth-year) #REQUIRED
          graduation-status (full-time|part-time|graduated|withdrawn) #REQUIRED>

=== RyderRaymond/assignment-1--databases--cs-365--fall-2024/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE student SYSTEM "student.dtd">

<student id="1234567">
  <name>
    <first-name>Gordon</first-name>
    <middle-name>Matthew</middle-name>
    <last-name>Sumner</last-name>
    <preferred-name>"Sting"</preferred-name>
  </name>
  <contact-info email="sting@thepolice.com" phone="212.123.4567" />
  <enrollment-info year-status="first-year" graduation-status="full-time">
    <gpa>4.0</gpa>
    <major>Music</major>
    <major>English</major>
    <advisor>Andy Summers</advisor>
    <date-enrolled>08-25-1969</date-enrolled>
    <graduation-date>05-01-1973</graduation-date>
  </enrollment-info>
</student>
